### ISSUE TITLE
Can not library ParallelGDDetect

### ISSUE THREAD

**Issue by WangKang-Leo** [amf71/ParallelGDDetect#1]
Dear

Congratulations for TRACERx tumor evolution publication. We are very interested in this package that detects GDD. However, after package installation (devtools::install_github('amf71/ParallelGDDetect')), I can not load the package. Maybe you have not given access to public?

Thanks/Kang

**Comment by amf71** [comment]
HI Kang, Thanks for picking this up. It was caused by a typo in the package name of the DESCRIPTION. It should now work for you.
