### ISSUE TITLE
Output from ParallelGDDetect

### ISSUE THREAD

**Issue by WangKang-Leo** [amf71/ParallelGDDetect#2]
Thanks for your R package!

If I want to know whether the GD occurred to a certain sample or not, which metrics should I check? I just want to know the binary results (GD or not GD) of the samples. 

The second question is if we have the longitudinal samples (pre/on/post-treatment), any suggestion on use of ParallelGDDetect

Looking forward to your reply!

**Comment by amf71** [comment]
Hi WangKang-Leo,

Thanks for your message. The tool doesn't do this exactly. Perhaps I should modify the readMe to make this clear. You have to actually put as an input how many GD events there are in each sample from a given tumour. This is determined broadly from the ploidy output of a copy number deconvolution tool such as ASCAT. More precisely we estimate the fraction of the genome with MajorCN >= 2 (MajorCN determined using ASCAT) and if this is >50% we consider that a genome doubling has occurred in that tumour sample (if >50% have MajCN >=3 then we think 2 GDs have occurred). 

This tool is for a case where you have multiple samples from the same tumour with GD (which it sounds like you may have) and you want to determine whether the GD events you're observing in your samples represent one clonal GD, ie that occurred in an ancestor cell giving rise to both your samples, or whether they represent two different GD events that occurred after this common ancestor which each led to the tumour cells in your separate samples. ParrallelGDDetect can help you distinguish these cases using subclonal mutation copy numbers. 

Hope this is helpful. Take a look at the example input to see if can try running on your samples. 

Alex

**Comment by WangKang-Leo** [comment]
> Hi WangKang-Leo,
> 
> Thanks for your message. The tool doesn't do this exactly. Perhaps I should modify the readMe to make this clear. You have to actually put as an input how many GD events there are in each sample from a given tumour. This is determined broadly from the ploidy output of a copy number deconvolution tool such as ASCAT. More precisely we estimate the fraction of the genome with MajorCN >= 2 (MajorCN determined using ASCAT) and if this is >50% we consider that a genome doubling has occurred in that tumour sample (if >50% have MajCN >=3 then we think 2 GDs have occurred).
> 
> This tool is for a case where you have multiple samples from the same tumour with GD (which it sounds like you may have) and you want to determine whether the GD events you're observing in your samples represent one clonal GD, ie that occurred in an ancestor cell giving rise to both your samples, or whether they represent two different GD events that occurred after this common ancestor which each led to the tumour cells in your separate samples. ParrallelGDDetect can help you distinguish these cases using subclonal mutation copy numbers.
> 
> Hope this is helpful. Take a look at the example input to see if can try running on your samples.
> 
> Alex

Thanks you for the very clear explanation, and it also makes sense for time-series samples! Wonderful bioinformatic tool!
